name: shop_http_2024
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  flutter_bloc:
  intl: ^0.19.0
  sqflite:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/shop_http.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/NoFoto.jpg
    - assets/images/shop_http.jpg
